name: CMake

on: [push, pull_request]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Install prerequisites
      run: |
        sudo apt update
        sudo apt install -y g++-5
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 90
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90

    - name: Install OpenCL driver for CPU
      run: sudo bash .github/scripts/install_intel_opencl.sh;

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: aplusb
      working-directory: ${{github.workspace}}/build
      run: ./aplusb

    - name: mandelbrot
      working-directory: ${{github.workspace}}/build
      run: ./mandelbrot

    - name: sum
      working-directory: ${{github.workspace}}/build
      run: ./sum

    - name: max_prefix_sum
      working-directory: ${{github.workspace}}/build
      run: ./max_prefix_sum